# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - main

pool: ADO-LX-ANTEPRD01-ArtefactPublishing

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: Private Docker Registry Eiffage [ENV PRD]

# - task: Docker@2
#   displayName: Build and Push
#   inputs:
#     command: buildAndPush
#     repository: testcxo/testimage # username/contosoRepository for DockerHub
#     tags:
#       1.0.1